# Generated by Django 4.1.7 on 2023-03-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='image',
            field=models.ImageField(blank=True, upload_to='contrats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='sinistres/%Y/%m/%d/'),
        ),
    ]
